#!/usr/bin/env node
import './test/harness/contract.mjs';
import './test/harness/tracks.mjs';
import './test/harness/run-lifecycle.mjs';
import './test/harness/validators.mjs';
import './test/harness/concurrency.mjs';
import './test/harness/cli.mjs';
import './test/harness/sync.mjs';
import './test/harness/coverage.mjs';
